### PR TITLE
fix XacroLoader.d.ts

### LINKED ISSUE #65: wrong ts.d for XacroLoader
According to [the ts.d](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.d.ts#L14) `.load` takes the parameters `url: string, onLoad: (xml: XMLDocument) => void, options?: XacroLoaderOptions`, but [the actual implementation](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.js#L13) (probably) takes a string and two functions, so the ts.d should probably say something like `load(url: string, onLoad: (xml: XMLDocument) => void, onError: (err: Error) => void): Promise<XMLDocument>` instead.

### PR DESCRIPTION
**Pull request by ajs124**
fixes #65

Not sure if the return type is correct, but AFAICT neither of them actually return a Promise.

### CODE REVIEW

File: src/XacroLoader.d.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ interface XacroLoaderOptions {
 
 export class XacroLoader {
 
-    load(url: string, onLoad: (xml: XMLDocument) => void, options?: XacroLoaderOptions): Promise<XMLDocument>;
-    parse(content: string, onLoad: (xml: XMLDocument) => void, options?: XacroLoaderOptions): Promise<XMLDocument>;
+    load(url: string, onLoad: (xml: XMLDocument) => void, onError: (err: Error) => void): void;
+    parse(content: string, onLoad: (xml: XMLDocument) => void, options?: XacroLoaderOptions): void;
```
Comment (gkjohnson) [inline src/XacroLoader.d.ts:15]: Thanks for the fix! If we're here can we update the `parse` function with the correct signature, as well? It should be the same change as for `load`. See here:

https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.js#L41

**Review by gkjohnson — APPROVED** [review]
Great, thanks! I'll try to get this published over the next week or so.
